version: 0.2
env:
  secrets-manager:
    DOCKERHUB_PASS: "docker/creds:DOCKER_PASS"
    DOCKERHUB_USERNAME: "docker/creds:DOCKER_LOGIN"
  variables:
    region: "eu-north-1"
    repository_uri: "050175524215.dkr.ecr.eu-north-1.amazonaws.com/isaenkobook"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ${region} --no-include-email)
      - REPOSITORY_URI=${repository_uri}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$COMMIT_HASH
      - echo Logging in to Docker Hub...
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  build:
    commands:
      - echo maven build
      - mvn clean install
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG